Experiment No.10

Name : Pranav menon\
PRN No.:25070123085\
Batch : ENTC B1

Aim of the Experiment : Study of the Pandas Library

In [142]:
# Introduction to Pandas
import pandas as pd
s = pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [143]:
# Introduction to Pandas
import pandas as pd
s = pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [144]:
# DataFrame Creation
import pandas as pd
data = {
          "Name":["A","B","C"],
          "Marks":[85,90,78]
}
df = pd.DataFrame(data)
df

  Name  Marks
0    A     85
1    B     90
2    C     78

In [145]:
# DataFrame Creation
import pandas as pd
data = {
          "Name":["A","B","C"],
          "Marks":[85,90,78]
}
df = pd.DataFrame(data)
print(df)

# df.head() and df.tail()

  Name  Marks
0    A     85
1    B     90
2    C     78

In [146]:
# To determine ths structure of a DataFrame
print(df.shape)

(3, 2)

In [147]:
# To determine ths structure of a DataFrame
print(df.size)

6

In [148]:
# To display the Coloumn Name
print(df.columns)

Index(['Name', 'Marks'], dtype='object')

In [149]:
# To identify the datatype
print(df.dtypes)

Name     object
Marks     int64
dtype: object

In [150]:
# To access Individual Column
print(df["Name"])

0    A
1    B
2    C
Name: Name, dtype: object

In [151]:
# To access Individual Column
print(df["Marks"])

0    85
1    90
2    78
Name: Marks, dtype: int64

In [152]:
# To access Specific Rows
print(df.loc[0,"Name"])
print(df.loc[0,"Marks"])
print(df.iloc[0,0])
print(df.iloc[2,1])

A
85
A
78

In [153]:
# To add a new Coloumn
df["Grade"] = ["First Class","Distinction","Second Class"]
print(df)

  Name  Marks         Grade
0    A     85   First Class
1    B     90   Distinction
2    C     78  Second Class

In [154]:
# To change the Marks of a Student
df.loc[0,"Marks"] = 88
print(df)
df.iloc[0,1] = 88
print(df)

  Name  Marks         Grade
0    A     88   First Class
1    B     90   Distinction
2    C     78  Second Class
  Name  Marks         Grade
0    A     88   First Class
1    B     90   Distinction
2    C     78  Second Class

In [155]:
# To delete a Coloumn
# inplace=True ----> Overwrites the Data
df1 = df.drop("Grade",axis=1)
print(df)
print(df1)

  Name  Marks         Grade
0    A     88   First Class
1    B     90   Distinction
2    C     78  Second Class
  Name  Marks
0    A     88
1    B     90
2    C     78

In [156]:
# To delete a Coloumn
df.drop("Grade",axis=1,inplace=True)
print(df)

  Name  Marks
0    A     88
1    B     90
2    C     78

In [157]:
# Mathematical Operations using Pandas
mean1 = df["Marks"].mean()
max1 = df["Marks"].max()
min = df["Marks"].min()
print(mean1)
print(max1)
print(min)

85.33333333333333
90
78

In [158]:
# Filtering of Data using Pandas
print(df[df["Marks"]>80])

  Name  Marks
0    A     88
1    B     90